name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

        # Node.js に内蔵されたパッケージマネージャ管理ツール
        # pnpmのバージョンを 明示的に指定して使える ようにする
      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        # 「--frozen-lockfile」ロックファイルが正確に再現されることを保証する
        # - pnpm-lock.yamlを絶対に変更しない
        # - ロックファイルと異なる状態ではエラーで停止
        # - CI環境での一貫性を完全保証
        run: pnpm install --frozen-lockfile 

      - name: Generate Prisma client
        # CI環境でPrismaクライアントコードを生成
        run: pnpm --filter api... db:generate

      - name: Run Biome lint
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm type-check

      - name: Run tests
        run: pnpm test

      - name: Build Next.js & Nest.js project
        run: pnpm build
